PFA_HEADERS = [
    "SNO",
    "PENSION NUMBER",
    "PFA NAME",
    "STAFF",
    "SURNAME",
    "OTHER NAMES",
    "GROSS PAY",
    "VOLUNTARY CONTRIBUTION",
    "EMPLOYEE CONTRIBUTION",
    "EMPLOYER CONTRIBUTION",
    "TOTAL",
]

SUMMARY_HEADERS = [
    "SNO",
    "PFA",
    "GROSSPAY",
    "VOL. CONTRIBUTION",
    "EMPLOYEE CONTRIBUTION",
    "EMPLOYER CONTRIBUTION",
    "TOTAL PENSION",
]
